# Generated by Django 4.1.7 on 2023-03-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmertable',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=100)),
                ('f_phone', models.CharField(max_length=100)),
                ('f_address', models.CharField(max_length=100)),
                ('f_email', models.CharField(max_length=100)),
                ('f_pass', models.CharField(max_length=100)),
                ('f_loca', models.CharField(max_length=100)),
                ('f1', models.CharField(default='', max_length=100)),
                ('f2', models.CharField(default='', max_length=100)),
                ('f3', models.CharField(default='', max_length=100)),
                ('f4', models.CharField(default='', max_length=100)),
                ('f5', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Logintable',
            fields=[
                ('lid', models.AutoField(primary_key=True, serialize=False)),
                ('l_email', models.CharField(max_length=150)),
                ('l_pass', models.CharField(max_length=50)),
                ('l_type', models.CharField(max_length=50)),
                ('l_status', models.CharField(max_length=50)),
            ],
        ),
    ]
