# Generated by Django 4.1.7 on 2023-03-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usertable',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=100)),
                ('u_phone', models.CharField(max_length=100)),
                ('u_address', models.CharField(max_length=100)),
                ('u_email', models.CharField(max_length=100)),
                ('u_pass', models.CharField(max_length=100)),
                ('u_loca', models.CharField(max_length=100)),
                ('u1', models.CharField(default='', max_length=100)),
                ('u2', models.CharField(default='', max_length=100)),
                ('u3', models.CharField(default='', max_length=100)),
                ('u4', models.CharField(default='', max_length=100)),
                ('u5', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
