# Generated by Django 4.1.7 on 2023-03-30 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usertable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_table',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('p_date', models.CharField(max_length=100)),
                ('p_name', models.CharField(max_length=100)),
                ('p_img', models.ImageField(upload_to='')),
                ('p_cat', models.CharField(max_length=100)),
                ('p_stock', models.CharField(max_length=100)),
                ('p_rate', models.CharField(max_length=100)),
                ('pro1', models.CharField(default='', max_length=100)),
                ('pro2', models.CharField(default='', max_length=100)),
                ('fid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.farmertable')),
            ],
        ),
    ]
