# Generated by Django 4.1.7 on 2023-04-02 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_investortable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schemetable',
            fields=[
                ('loanid', models.AutoField(primary_key=True, serialize=False)),
                ('loan_name', models.CharField(max_length=100)),
                ('type_loan', models.CharField(max_length=100)),
                ('repayment', models.ImageField(upload_to='')),
                ('docu', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('interest', models.CharField(max_length=100)),
                ('loan1', models.CharField(default='', max_length=100)),
                ('loan2', models.CharField(default='', max_length=100)),
                ('invid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.investortable')),
            ],
        ),
    ]
