# Generated by Django 4.1.7 on 2023-04-03 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_schemetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loantable',
            fields=[
                ('appid', models.AutoField(primary_key=True, serialize=False)),
                ('app_amount', models.CharField(max_length=100)),
                ('docmnt1', models.ImageField(upload_to='')),
                ('docmnt2', models.ImageField(upload_to='')),
                ('docmnt3', models.ImageField(upload_to='')),
                ('app1', models.CharField(default='', max_length=100)),
                ('app2', models.CharField(default='', max_length=100)),
                ('loanid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.schemetable')),
                ('uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.usertable')),
            ],
        ),
    ]
