# Generated by Django 4.1.7 on 2023-04-04 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_loantable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loantable',
            name='uid',
        ),
        migrations.AddField(
            model_name='loantable',
            name='fid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.farmertable'),
        ),
    ]
