# Generated by Django 4.1.7 on 2023-04-11 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_loantable_uid_loantable_fid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply_table',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=100)),
                ('s_img', models.ImageField(upload_to='')),
                ('s_cat', models.CharField(max_length=100)),
                ('s_stock', models.CharField(max_length=100)),
                ('s_rate', models.CharField(max_length=100)),
                ('sup1', models.CharField(default='', max_length=100)),
                ('sup2', models.CharField(default='', max_length=100)),
                ('fid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.farmertable')),
            ],
        ),
    ]
