# Generated by Django 4.1.7 on 2023-04-11 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_supply_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply_cart_table',
            fields=[
                ('s_cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_cart_date', models.CharField(max_length=100)),
                ('s_cart_name', models.CharField(max_length=100)),
                ('s_cart_cat', models.CharField(max_length=100)),
                ('s_cart_stock', models.CharField(max_length=100)),
                ('s_cart_rate', models.CharField(max_length=100)),
                ('s_cart1', models.CharField(default='', max_length=100)),
                ('s_cart2', models.CharField(default='', max_length=100)),
                ('s_cart3', models.CharField(default='', max_length=100)),
                ('fid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.farmertable')),
                ('sid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.supply_table')),
            ],
        ),
    ]
